/**
 * @file Version.h
 * @brief Version information for Imhotep Engine
 *
 * This file is auto-generated by CMake from Version.h.in
 * Do not edit directly - modify Version.h.in or CMakeLists.txt instead.
 */

#pragma once

#include <string>

namespace imhotep
{

/**
 * @brief Version information and utilities
 *
 * Provides compile-time version constants and runtime version queries.
 * Version follows Semantic Versioning 2.0.0 (https://semver.org/)
 *
 * - MAJOR: Incompatible API changes
 * - MINOR: Backwards-compatible functionality additions
 * - PATCH: Backwards-compatible bug fixes
 */
class Version
{
public:
    /// Major version number (breaking changes)
    static constexpr int MAJOR = 0;

    /// Minor version number (new features, backwards-compatible)
    static constexpr int MINOR = 1;

    /// Patch version number (bug fixes, backwards-compatible)
    static constexpr int PATCH = 0;

    /// Full version string (e.g., "0.1.0")
    static constexpr const char* STRING = "0.1.0";

    /**
     * @brief Get formatted version string with prefix
     * @return Version string (e.g., "v0.1.0")
     */
    static std::string GetVersionString()
    {
        return std::string("v") + STRING;
    }

    /**
     * @brief Get full application banner for logging
     * @return Banner string with engine name and version
     */
    static std::string GetBanner()
    {
        return "Imhotep Engine " + GetVersionString();
    }

    /**
     * @brief Check if version is at least the specified version
     * @param major Required major version
     * @param minor Required minor version (default: 0)
     * @param patch Required patch version (default: 0)
     * @return True if current version >= required version
     */
    static constexpr bool IsAtLeast(int major, int minor = 0, int patch = 0)
    {
        if (MAJOR != major) return MAJOR > major;
        if (MINOR != minor) return MINOR > minor;
        return PATCH >= patch;
    }
};

} // namespace imhotep
