input:
  keyMappings:
    # spinLeft: [Z, ArrowUp]
    # spinRight: [X]
    # down: [ArrowDown]
    # left: [ArrowLeft]
    # right: [ArrowRight]
    # place: [Space]
    # pause: [ESC, p]
    forward: [W, ArrowUp]
    left: [A, ArrowLeft]
    back: [S, ArrowDown]
    right: [D, ArrowRight]
    turn: [Space]
    quit: [ESC]
    zoomIn: [ScrollUp]
    zoomOut: [ScrollDown]
  scriptPath: input.lua

game:
  resourcePath: ../res/
  logPath: ../logs/tetris.log
  appName: VaporwaveTetris
  scenePath: scenes/TetrisScene.yaml
  debug: true
  htmlPath: ui/templates/game.html
  cssPath: ui/styles/game.css
  luaStatePath: ui/state/game.lua
  templateName: VaporwaveTetris

window:
  targetFPS: 60
  windowWidth: 1400
  windowHeight: 840
