input:
  keyMappings:
    forward: [W, ArrowUp]
    left: [A, ArrowLeft]
    back: [S, ArrowDown]
    right: [D, ArrowRight]
    quit: [ESC]
    zoomIn: [ScrollUp]
    zoomOut: [ScrollDown]
  scriptPath: input.lua

game:
  resourcePath: ../res/
  logPath: ../logs/terrain.log
  appName: TerrainTest
  scenePath: scenes/TerrainTestScene.yaml
  debug: true
  htmlPath: ui/templates/terrain.html
  cssPath: ui/styles/terrain.css
  luaStatePath: ui/state/terrain.lua
  templateName: TerrainTest

window:
  targetFPS: 60
  windowWidth: 1400
  windowHeight: 840
